title: "Picklebitches"
author: "TSS Webdev"
description: "Made by <b style=\"color: #31B426;\">&lt;TSS Webdev Team></b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/index.html", title: "Home", icon: home, url: "https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FThe-Salisbury-School%2Fpicklebitches-webdev"}
  - {title: "Videos & Media", url: "https://google.com", sidebaricon: photo-film}
  - {title: "Shop", url: "https://google.com", sidebaricon: bag-shopping}
  - {title: "Pickle Pups", url: "https://google.com", sidebaricon: dog}
  - {file: "/README.md", title: "About the Bitches", sidebaricon: question}
  - {title: "My Account", url: "https://google.com", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/The-Salisbury-School"}
  - {title: TikTok, icon: tiktok, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
